name: Maestro Test

on:
  push:
    branches:
      - main

jobs:
  maestro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Android system image
        uses: actions/cache@v3
        with:
          path: |
            ~/.android
            ~/.gradle
            $ANDROID_HOME/system-images
          key: android-system-image-${{ runner.os }}-api30

      - name: Install system image
        run: sdkmanager "system-images;android-30;google_apis;x86"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86"
          emulator -avd test -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          boot_completed=""
          until [ "$boot_completed" = "1" ]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          echo "✅ Emulator is ready"

      - name: Cache Maestro binary
        uses: actions/cache@v3
        with:
          path: ~/.maestro
          key: maestro-binary-${{ runner.os }}

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro test
        run: maestro test test-flows/smoke_test.yaml
