name: Run Maestro Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3
          script: echo "Emulator ready"

      - name: Install Sample APK
        run: |
          wget https://github.com/saucelabs/sample-app-mobile/releases/download/v2.7.1/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk -O sample-app.apk
          adb install sample-app.apk

      - name: Run Maestro Tests
        run: maestro test test-flows/smoke_test.yaml

      - name: Upload Maestro Report (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report
          path: maestro-output/

      # Optional: Integrate with Maestro Cloud if API key is available
      # - name: Upload results to Maestro Cloud
      #   run: maestro cloud test --apiKey ${{ secrets.MAESTRO_CLOUD_API_KEY }} --app sample-app.apk --tests test-flows/
